### ISSUE TITLE
Backend Not Configured Well

### ISSUE THREAD

**Issue by AskitEndo** [jinx-vi-0/passop#1]
The backend code is although working but is not error safe.
implementing proper status codes or try catch blocks to, encounter exact reason of failure In case of Miss happening.

**Comment by devarsheecodess** [comment]
assign this to me with gssoc24-extd label. I have worked on a similar project and i am sure i can fix this

**Comment by adarsh-site** [comment]
I'm assigning this issue to both of you @AskitEndo @devarsheecodess . Please improve the code and then submit a detailed PR.

Note- Do not copy paste code directly from any AI tools.

**Comment by AskitEndo** [comment]
@jinx-vi-0 I have Fixed The Issue  and also I have added the gitignore file for the backend 
kindly verify and merge accordingly, review the code
