### ISSUE TITLE
Add New Feature: Dynamic Messages 

### ISSUE THREAD

**Issue by prateek2102** [jinx-vi-0/passop#10]
Right now we are using hard-coded messages, if we need to change an error message or any message in our app we will need to change it everywhere. 
Fix: We can create a constants.js file and export our error messages and call them inside our app which will help us to change the messages only in our constant file and it will reflect everywhere.
Reference -
![image](https://github.com/user-attachments/assets/d81694a6-ac22-4e8a-89a3-f84967858157)

**Comment by prateek2102** [comment]
@jindalpriyanshu101 please assign it to me, would love to contribute on this.

**Comment by jindalpriyanshu101** [comment]
Assigned, go ahead :D

Suggestion: you can add multiple variables for to show different error messages at times.
