### ISSUE TITLE
[FEATURE] : Adding a way to navigate to the home page from the sign-up page

### ISSUE THREAD

**Issue by HemantBatra873** [jinx-vi-0/passop#101]
**Problem**
When you are at the sign-up page and suppose you want to go back to the home page without signing in there is no way to do that . Also if you click at the logo . You should be directed to the home page but currently that functionality is not present .

---

**Solution**
What I am suggesting is adding a navigation to the home-page whenever we click on the logo and the button on the home page that takes you to the login page should be modified when we are on the sign-in page itself . That button can be used to take you back at the home page . 

---

**Alternative Solution**
Alternative solution is that I don't add the navigational functionality which i proposed for the logo and instead of changing the sign-up page navigation button on the sign-up page to home button on sign-up page . I simply add a back button on the top left .

---

Please assign this to me under gssoc-ext , level and hacktoberfest-accepted

**Comment by adarsh-site** [comment]
we're still in the development phase. The end idea is that login/signin page should be the main page. Only login users can access the home page.

**Comment by HemantBatra873** [comment]
> we're still in the development phase. The end idea is that login/signin page should be the main page. Only login users can access the home page.

Oh okay I'll find out something else to contribute in your project .
