### ISSUE TITLE
Footer UI

### ISSUE THREAD

**Issue by RitikaMaha** [jinx-vi-0/passop#104]
The footer is too small and lacks visual balance, making it appear cramped and unappealing. The text size and layout are not proportional to the rest of the page, giving it an unfinished look. The heart icon appears awkwardly placed and does not blend well with the overall design. More icons like discover button or some intresting stuff should be their at the end.
So @passop pl do assign me this task
![WhatsApp Image 2024-10-15 at 21 13 02_3895cbfc](https://github.com/user-attachments/assets/edaf5b62-ea59-4ac3-b3dd-4a61580be8a8)

**Comment by adarsh-site** [comment]
already issue #93
