### ISSUE TITLE
Feature: Create a Landing page for the website

### ISSUE THREAD

**Issue by Tamanna225** [jinx-vi-0/passop#107]
**Current Issue:**

At present, when users visit the website, they are directly taken to the page for password manager. While this is part of the website's functionality, it creates a problem because users are prompted to store passwords before logging in. Since the passwords won’t actually be saved until after login, this could cause confusion or frustration for users.

**Proposed Solution:**

Instead of directly loading the password storage page, we should implement a landing page that provides information about the website's purpose and functionality. From this landing page, users can then navigate to the actual functionality page, where they can securely manage their passwords after logging in. This ensures a smoother and more logical user experience, where users first understand what the site offers and can access features like password storage only once they are logged in and authenticated.

If found feasible Please assign this to me under gssoc-ext , level and hacktoberfest-accepted

**Comment by adarsh-site** [comment]
The login/signin page should be the main page. Only login users can access the home page where they can store password. If you want to create a login/signUp page you are good to go.
