### ISSUE TITLE
Navbar Layout Misalignment After User Sign-In

### ISSUE THREAD

**Issue by Lokesh-Bijarniya** [jinx-vi-0/passop#108]
**Describe the bug**
After signing in, the layout of the navbar becomes misaligned. Specifically, the elements on the right side of the navbar (e.g., export, import, sign out) are not properly aligned or spaced, resulting in a cluttered appearance.

**To Reproduce**
1. Sign in to the application.
2. Observe the navbar layout after the page loads.
3. Notice the misalignment of the navbar items.

**Expected behavior**
The navbar items should remain consistently spaced and aligned, even after signing in, for a clean and organized appearance.

**Screenshots**
<img width="1439" alt="Screenshot 2024-10-16 at 5 30 27 PM" src="https://github.com/user-attachments/assets/eaee24c6-266d-487a-ad7b-2bb6ba3eaa67">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, Brave]

**Additional context**
This issue occurs after a user signs in, but it does not appear on the initial load of the homepage. The issue might be related to how the navbar is styled or rendered upon sign-in.

**Comment by Lokesh-Bijarniya** [comment]
@jinx-vi-0 Could u assign me under gssoc & hacktober.

**Comment by adarsh-site** [comment]
@jindalpriyanshu101 can you please look into this?

**Comment by jindalpriyanshu101** [comment]
@Lokesh-Bijarniya Can you attach a video demonstration of this bug as well? for better context

**Comment by Lokesh-Bijarniya** [comment]
https://github.com/user-attachments/assets/375158b1-cfed-4bd4-a2fc-dfc642941bc2

**Comment by jindalpriyanshu101** [comment]
Alright then, you're good to go. ;)
