### ISSUE TITLE
Better lord-icon Sign In button 

### ISSUE THREAD

**Issue by AskitEndo** [jinx-vi-0/passop#110]
**Describe the bug**
The Sign-in button although working doesn't have the proper icons

**To Reproduce**
1. Go to 'Home Page'
2. See error
![Screenshot 2024-10-16 212010](https://github.com/user-attachments/assets/879a9054-c5ce-4feb-811c-8e49febb37e7)

**Comment by AskitEndo** [comment]
@jindalpriyanshu101 @jinx-vi-0 Do assign the tags and let me fix this quick issue!

**Comment by jindalpriyanshu101** [comment]
Do you mind showing the icons you would like to use then?

**Comment by AskitEndo** [comment]
> Do you mind showing the icons you would like to use then?

Sure.
![Screenshot_2024-10-19-12-28-05-13_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/d5dc0dd6-a6f9-40f0-8931-ca91918ed80b)

This is a animated-lord-icon

**Comment by AskitEndo** [comment]
@jindalpriyanshu101 @jinx-vi-0 Do add the necessary tags,as I have already worked on it, just need to push
