### ISSUE TITLE
[FEATURE] Setting up a project made easier 

### ISSUE THREAD

**Issue by kartik1112** [jinx-vi-0/passop#114]
It is always frustrating to read every project documentation to have different command to start the backend and the frontend. like in this "cd backend && node server.js" for running the backend and "npm run dev" to start the frontend.

I feel a better and scalable approach can be a simple command like "npm run dev:frontend" to start the frontend in dev environment and "npm run dev:backend" to start the backend in dev environment. 

This way it can be clearly managed even when the project scales also it will be easier to start contributing to the project.

Please assign the issue to me and I'll work on it ASAP.

**Comment by kartik1112** [comment]
@jindalpriyanshu101 please look into this once.

**Comment by jindalpriyanshu101** [comment]
Hey there, even though it sounds nice but i believe using traditional way might be suitable for the absolute beginners as they may find it hard to debug whenever they have to.

However, would like to know your views on it? @jinx-vi-0

**Comment by adarsh-site** [comment]
I completely agree that the traditional approach might be the best, especially for beginners.
