### ISSUE TITLE
Adding Oauth for login and signup

### ISSUE THREAD

**Issue by LitZeus** [jinx-vi-0/passop#117]
**Is your feature request related to a problem? Please describe.**
Adding the OAuth will make the sign in and registering in the app easy and quick under 2 clicks and the information/credentials will also be handled securely

**Describe the solution you'd like**
Implementing OAuth using the google firebase will increase the quality and efficiency of the app

**Describe alternatives you've considered**
We can implement it using the GCP but firebase integration is stronger than GCP.

**Additional context**
Add this to make the login quick and it will indirectly make users to use the app more

**Comment by adarsh-site** [comment]
Assigned @LitZeus
