### ISSUE TITLE
The greeting workflow is broken

### ISSUE THREAD

**Issue by LitZeus** [jinx-vi-0/passop#118]
**Describe the bug**
the greeting workflow of the repo is not working properly, will give the screenshot to understand more

**To Reproduce**
1. Go to issues
2. Click on create issue
3. Type the issue and submit
4. See error after a min or two

**Expected behavior**
It should greet the user properly!

**Screenshots**
![image](https://github.com/user-attachments/assets/4d654167-8f0a-429a-9f2e-972903b22538)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge

**Additional context**
It says that the docker container is messing with the workflow

**Comment by adarsh-site** [comment]
Assigned @LitZeus
