### ISSUE TITLE
Bug: Decrypt Function Fails Due to Incorrect Parameter Passing

### ISSUE THREAD

**Issue by VinaySatrasala** [jinx-vi-0/passop#119]
Here's the updated suggestion for the GitHub issue with the actual code included:

### Title
**Bug: Decrypt Function Fails Due to Incorrect Parameter Passing**

### Description
I encountered an issue in the password decryption logic in the `server.js` file. The `decrypt` function is designed to accept a single string containing both the IV and the encrypted data, but in the `GET /` route handler, an object containing `iv` and `encryptedData` is passed instead. This leads to a `TypeError` when trying to split the input string.

**Steps to Reproduce:**
1. Start the server and call the `GET /` endpoint.
2. Observe the console error message indicating a failure in the decryption process.

**Error Message:**
```
TypeError: text.split is not a function or its return value is not iterable
```

**Code Snippet:**

Here’s the relevant code from the `server.js` file:

```javascript
// Decrypt function
const decrypt = (text) => {
  const [iv, encryptedData] = text.split(":");
  const ivBuffer = Buffer.from(iv, "hex");

  const decipher = crypto.createDecipheriv(
    "aes-256-cbc",
    Buffer.from(ENCRYPTION_KEY),
    ivBuffer
  );
  let decrypted = decipher.update(encryptedData, "hex", "utf-8");

  decrypted += decipher.final("utf-8");

  return decrypted;
};

// GET / route handler
app.get("/", async (req, res) => {
  try {
    const db = client.db(dbName);
    const collection = db.collection("passwords");
    const passwords = await collection.find({}).toArray();
    const decryptedPassword = passwords.map((item) => {
      const [iv, encryptedData] = item.password.split(':'); // Incorrectly passing an object
      return { ...item, password: decrypt({ iv, encryptedData }) }; // This will cause an error
    });
    res.status(200).json(decryptedPassword);
  } catch (error) {
    console.error("Error fetching passwords:", error);
    res.status(500).json({ success: false, message: "Internal Server Error" });
  }
});
```

**Suggested Fix:**
Update the `app.get("/")` route handler to call the `decrypt` function with the full encrypted password string:

```javascript
const decryptedPassword = passwords.map((item) => {
  return { ...item, password: decrypt(item.password) }; // Pass the correct argument
});
```

This change will ensure the decryption process works correctly by passing the proper argument to the `decrypt` function.

---

i will raise a PR if that issue is clear to you.

**Comment by adarsh-site** [comment]
@jindalpriyanshu101 can you please look into this.

**Comment by jindalpriyanshu101** [comment]
You're good to proceed @VinaySatrasala

**Comment by VinaySatrasala** [comment]
I have raised a pr regarding this do check it out : https://github.com/jinx-vi-0/passop/pull/120

**Comment by adarsh-site** [comment]
Good Work @VinaySatrasala
