### ISSUE TITLE
Missing docker ignore file

### ISSUE THREAD

**Issue by vivekrawat21** [jinx-vi-0/passop#121]
**Describe the bug**
.dockerignore file  is missing from the project

**Expected behavior**
The .dockerignore file functions similarly to a .gitignore file, and it is used to specify which files and directories should be ignored when building the Docker image. This helps to reduce the image size and exclude unnecessary files from the build context

**Comment by vivekrawat21** [comment]
@jinx-vi-0  please assign me this issue

**Comment by jindalpriyanshu101** [comment]
Not required as of now, it'll be done manually. Thanks for showing interest ;D
