### ISSUE TITLE
Improving Password Encryption with AES-256 and PBKDF2 algos!

### ISSUE THREAD

**Issue by Ishratnoori** [jinx-vi-0/passop#122]
Hello Maintainers,

I’d like to help with the passOP project by  "Enhancing the password encryption" by upgrading to a more secure method.
This feature will improve the security of the password manager system.

Could you please assign this issue to me? 
I’m looking forward to contributing!

Best regards,  
Ishrat :) 
(Please assign me under gssoc-ext and hacktoberfest;))

**Comment by adarsh-site** [comment]
@jindalpriyanshu101 can you please look into this .

**Comment by jindalpriyanshu101** [comment]
hi @Ishratnoori, we would love to know how you're going to enhance the current encryption. please explain your approach

**Comment by Ishratnoori** [comment]
Hi @jindalpriyanshu101!  As I'm focusing on cybersecurity, I'm planning to enhance encryption by using a combination of AES-256 and PBKDF2. This is my basic idea:

1. AES-256 Encryption : encrypts passwords with  strong 256-bit key to keep data safe
2. PBKDF2 Key Derivation: I’ll use pbkdf2 to create the encryption key, and applying multiple rounds of hashing. this makes it harder for attackers to crack

Together, AES-256 nd PBKDF2 make the encryption tougher to break, also increases security. let me know if u'd like to add anything!!

**Comment by jindalpriyanshu101** [comment]
Sounds good, start working on it @Ishratnoori

**Comment by Ishratnoori** [comment]
Hi @jindalpriyanshu101,

I’ve implemented the password encryption enhancements using AES-256 and PBKDF2. 
The changes are ready for review. 
Please check them out and merge if everything looks good. Lemme know if you have any suggestions or see any areas for further improvement!

Thanks a ton!

**Comment by jindalpriyanshu101** [comment]
Hey @Ishratnoori is there any update on this issue?

**Comment by Ishratnoori** [comment]
Hi @jindalpriyanshu101 and @jinx-vi-0,

I have successfully pushed the full AES-256 and PBKDF2 encryption enhancements in the **new-feature-branch**. You can find the changes in the pull request I created.

Thank you for your guidance throughout this process!

**Comment by jindalpriyanshu101** [comment]
Hi @Ishratnoori, i'm expecting you to raise your changes before 6pm today. And in-case you're unable to resolve those merge conflicts, contact me through discord so that actual changes can be pushed and merged.

**Comment by Ishratnoori** [comment]
![Uploading image.png…]()
This is the output

**Comment by adarsh-site** [comment]
times up.
