### ISSUE TITLE
The linkedin and twitter are not navigating to their own websites

### ISSUE THREAD

**Issue by gurramkarthiknetha** [jinx-vi-0/passop#124]
<img width="636" alt="image" src="https://github.com/user-attachments/assets/d841b1f5-cf59-411b-b8b3-c388cf0284b6">

**Comment by gurramkarthiknetha** [comment]
The linkedin and twitter are not navigating to their own websites i want to fix this issue please assign this issue under hacktober feast accepted label

**Comment by jindalpriyanshu101** [comment]
icons aren't navigating because they doesn't exists for passop yet. Thanks for showing interest in this project.
