### ISSUE TITLE
[Documentation Update]: Add GitHub Repository Stats to README.md

### ISSUE THREAD

**Issue by noobrehan18** [jinx-vi-0/passop#125]
**Is your feature request related to a problem? Please describe.**

The issue involves adding a table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions in the repository at a glance.
**Describe the solution you'd like**
Suggested Change

### **Steps to Implement:**

1-Create a table in the README.md file displaying the following repository statistics:
Stars
Forks
Open Issues
Open Pull Requests
Closed Pull Requests
2-Use markdown syntax to include badges or icons for each statistic, along with dynamic links to the corresponding sections of the repository.

<img width="820" alt="Screenshot 2024-10-22 at 10 31 42 PM" src="https://github.com/user-attachments/assets/b836700a-fdd4-4a28-ab09-45fd0629d35f">
like this

**Comment by jindalpriyanshu101** [comment]
Let me know if you're still up to work on it? @REHAN-18

**Comment by noobrehan18** [comment]
> Let me know if you're still up to work on it? @REHAN-18
yes but  its not assign to me @jinx-vi-0

**Comment by noobrehan18** [comment]
@jindalpriyanshu101 I want to work

**Comment by noobrehan18** [comment]
@jindalpriyanshu101 can you give me level label !!

**Comment by jindalpriyanshu101** [comment]
Alright then, you're good to go @REHAN-18

**Comment by noobrehan18** [comment]
@jindalpriyanshu101 see pr #133  done this !!

**Comment by jindalpriyanshu101** [comment]
Hey @REHAN-18, PRs are managed by @jinx-vi-0. Let him take his time to analyse and merge.

**Comment by noobrehan18** [comment]
@jindalpriyanshu101 OK SIR !!
