### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by PriyaD17** [jinx-vi-0/passop#127]
The application is active regardless how much time has passed, this poses as a security risk considering the saved passwords can be copied anytime (even after long duration of inactivity) 
This issue proposes adding **session timeout functionality to enhance application security**. The feature will track user activity and automatically log out users after a defined period of inactivity.

### Suggested Implementation:
- **Customisable timeout**: Allow users to configure their timeout duration in settings.
- **Alert before logging out**: Display a warning message before automatic logout, giving users a chance to extend their session.
- **Timeout Functionality**: Create a function to check elapsed time since the last interaction.
- **Logout Procedure**: Define actions to take upon timeout, such as clearing session data or redirecting to the login page.

**Comment by jindalpriyanshu101** [comment]
This feature actually sounds good, but make sure that you're not allowing more than 10mins for custom timeout selection.

**Comment by jindalpriyanshu101** [comment]
You're good to go @PriyaD17

**Comment by jindalpriyanshu101** [comment]
any update @PriyaD17?

**Comment by jindalpriyanshu101** [comment]
Marked as up-to-grab
