### ISSUE TITLE
Deleting One Password Deletes All Passwords

### ISSUE THREAD

**Issue by PriyaD17** [jinx-vi-0/passop#128]
There is a critical bug where attempting to **delete a single password results in the deletion of all stored passwords**.

### Steps to Reproduce:
1. Open the application.
2. Save passwords of different sites .
3. Select a single password and initiate deletion.

**Comment by jindalpriyanshu101** [comment]
Hey @PriyaD17 , can you include a screenshot/Video demonstrating this bug?

**Comment by PriyaD17** [comment]
[screen-capture.webm](https://github.com/user-attachments/assets/4f7fc781-d84f-4140-8ca1-e290317bc575)

**Comment by jindalpriyanshu101** [comment]
Alright then, @PriyaD17 You can start working on it ;D

**Comment by AADESHak007** [comment]
Hey @jindalpriyanshu101 may I work on this issue

**Comment by jindalpriyanshu101** [comment]
> Hey @jindalpriyanshu101 may I work on this issue

@PriyaD17 Any update? expecting your responce by 10PM, otherwise it'll be assigned to someone else.

**Comment by KGupta2601** [comment]
@jindalpriyanshu101 Kindly assign me this issue

**Comment by jindalpriyanshu101** [comment]
> @jindalpriyanshu101 Kindly assign me this issue

Assigned.
