### ISSUE TITLE
I want to Enhance the Error popup of Url Intput 

### ISSUE THREAD

**Issue by Sambashivarao-Boyina** [jinx-vi-0/passop#136]
**Is your feature request related to a problem? Please describe.**
Present the pop up of the error for validations of URL is not set properly 

![Screenshot from 2024-10-26 22-00-59](https://github.com/user-attachments/assets/ed9ccd2d-00ea-4639-91f9-bdbfcee158dc)
![Screenshot from 2024-10-26 22-01-11](https://github.com/user-attachments/assets/325c0595-c0d7-45d5-9bd2-89acb3cea4bf)

**Describe the solution you'd like**
I want to place it at the bottom of the input and also change its style and structure more effectively.

**Additional context**
I want to contribute this issue of **gssoc-ext**, **hacktoberfest-2024** , please assign me this issue and add the labels

**Comment by adarsh-site** [comment]
Placing it at the bottom affects the UI each time it pops up. What is your view on this?
