### ISSUE TITLE
I want to create a coustomized popup

### ISSUE THREAD

**Issue by Sambashivarao-Boyina** [jinx-vi-0/passop#137]
**Is your feature request related to a problem? Please describe.**
Present you are you are using a normal inbuilt popup I now match with the design of the website 

![Screenshot from 2024-10-26 22-03-06](https://github.com/user-attachments/assets/15ab5808-222d-47ac-a1c1-88d92d7e61a4)

**Describe the solution you'd like**
I want to create a custompop  for this which matching with your UI of the website.  

**Additional context**
Please assign me this issue under **gssoc-ext**, **hacktoberfest2024**. let me contribute to this project

**Comment by aditya-nv-06** [comment]
Can you assign this issue to me under gssoc

**Comment by jindalpriyanshu101** [comment]
Hi @Sambashivarao-Boyina , any update on the progress?

**Comment by Sambashivarao-Boyina** [comment]
Sorry I cannot able to setup the code in my system it is not connecting to backend

**Comment by jindalpriyanshu101** [comment]
> Sorry I cannot able to setup the code in my system it is not connecting to backend

You can go through the setup guide for that ;D are you working on this issue?

**Comment by jindalpriyanshu101** [comment]
Hey @Sambashivarao-Boyina complete your PR by today, otherwise it's not going to get counted as GSSoC Contribution

**Comment by adarsh-site** [comment]
times up.
