### ISSUE TITLE
fix: Website URL Validation

### ISSUE THREAD

**Issue by 17arindam** [jinx-vi-0/passop#14]
currently there is no website url validation . I want to integrate a website url validation using regular expression .

**Comment by jindalpriyanshu101** [comment]
Describe your approach first?

**Comment by 17arindam** [comment]
I will use regular expression check when user enters a url if its a valid url format it will be added otherwise it will ask to enter a valid url

**Comment by pranavi2** [comment]
Hey! I'd love to take on this issue if it's still available. My approach involves using a well-tested URL validation library like validator.js to ensure we catch more edge cases beyond what regex alone would handle. After the initial check, I’ll also add an async request to confirm the URL is actually reachable. Lastly, I'll add real-time feedback while users type, to enhance the overall experience. Let me know if I can be assigned!

**Comment by pranavajith** [comment]
@jindalpriyanshu101 Could I be assigned this issue? Would love to contribute this way!

**Comment by jindalpriyanshu101** [comment]
Let @jinx-vi-0 decide.

**Comment by pranavajith** [comment]
Noted. Thanks! Will wait for update from @jinx-vi-0

**Comment by adarsh-site** [comment]
@pranavajith website validation has already been implemented.

**Comment by pranavajith** [comment]
Noted. Got confused cause the issue seemed open.
