### ISSUE TITLE
Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [jinx-vi-0/passop#142]
Wanted to do the following changes :-

1) Enhance the project structure
2) Add star our repository section
3) Add the project structure
4) Add need help with the basics section
5) Enhance the pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the issue process section

**Comment by adarsh-site** [comment]
We are no longer accepting document changes.
