### ISSUE TITLE
Want to add security 

### ISSUE THREAD

**Issue by Dipanita45** [jinx-vi-0/passop#144]
Please assign me the issue 
@jinx-vi-0

**Comment by adarsh-site** [comment]
can you please describe the problem and your approach ?

**Comment by Dipanita45** [comment]
Want to add security to protect the website against harms

**Comment by adarsh-site** [comment]
I still have difficulty understanding. Could you please elaborate on it a bit more?

**Comment by Dipanita45** [comment]
Necessary security for this website

**Comment by jindalpriyanshu101** [comment]
Kindly explain your approach @Dipanita45. On how you plan to add security to this project?

**Comment by Dipanita45** [comment]
I will add security file in.md extension

**Comment by Dipanita45** [comment]
Please assign me this issue

**Comment by jindalpriyanshu101** [comment]
What do you mean? what kind of security fits in a .md file?? Explain it in details i'm not expecting an reply directly from emails this time. @Dipanita45

**Comment by Dipanita45** [comment]
Necessary security like how to report, vulnerability,....  etc

**Comment by jindalpriyanshu101** [comment]
Doesn't seem meaningful to me. Closing
