### ISSUE TITLE
Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by itshivams** [jinx-vi-0/passop#145]
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

and have to add sitemap.xml and robots file for search engine to crawl our site.

**Comment by adarsh-site** [comment]
hey @jindalpriyanshu101 , what's your view on this ?

**Comment by jindalpriyanshu101** [comment]
> hey @jindalpriyanshu101 , what's your view on this ?

I think we may need this if you have plans to deploy this project. @jinx-vi-0

**Comment by jindalpriyanshu101** [comment]
@myselfshivams Let us know if you're still up to work on this issue?

**Comment by KGupta2601** [comment]
@jindalpriyanshu101 please assign me this issue
I would like to work on it
Also please give the level label

**Comment by jindalpriyanshu101** [comment]
> @jindalpriyanshu101 please assign me this issue I would like to work on it Also please give the level label

Sure, you're assigned. good to go ahead. but do share your approach?

**Comment by KGupta2601** [comment]
@jindalpriyanshu101 approach includes the following
1)Adding Meta Tags in index.html for
Title tags
Description tags
Keywords tags
Robots meta tag
Open Graph tags

2)Implementing Dynamic Meta Tags by using a library like react-helmet

3)Creating sitemap.xml and Creating robots.txt in public folder

4)Updating build process and checking server configuration
