### ISSUE TITLE
Efficient Rendering of the website 

### ISSUE THREAD

**Issue by AADESHak007** [jinx-vi-0/passop#146]
**Is your feature request related to a problem? Please describe.**
Currently you are using CONTEXT API for state management which manages the state but it does not efficiently reloads the website .
There are libraries like REDUX , RECOIL etc for that purpose .
 

**Describe the solution you'd like**
I want to use RECOIL for the management of state so that the re-rendering is occurring more efficiently .   
#### Assign this issue to me .

**Additional context**
![Screenshot 2024-11-02 085924](https://github.com/user-attachments/assets/74d63f1a-11bf-43e5-9cd9-8e7c44b49de1)

**Comment by adarsh-site** [comment]
Assigned @AADESHak007

**Comment by jindalpriyanshu101** [comment]
Any update on progress? @AADESHak007

**Comment by AADESHak007** [comment]
Will complete it by tomorrow 8pm . @jindalpriyanshu101 really sorry brother had to undergo a test.

**Comment by AADESHak007** [comment]
@jindalpriyanshu101 bro I am really sorry for the delay  . I am facing some errors . I will try to complete it before midnight .
