### ISSUE TITLE
Better UI for the Homepage

### ISSUE THREAD

**Issue by Ayush215mb** [jinx-vi-0/passop#18]
I understand that your project is mostly backend based but still you need a good looking UI for sharing your project.
I can help you with that if you assign me this issue and other than that I would also love to connect with you as I'm also a college student from Kolkata and I saw that you also study at IEM.

**Comment by adarsh-site** [comment]
I haven't thought about updating the UI, but if your work impresses me, I will merge your pull request. Assigned @Ayush215mb 

You can find all my social on my GitHub page.

**Comment by Ayush215mb** [comment]
Thanks for assigning me this.
I will complete it by tomorrow and create the PR with the screenshot of the new UI.

**Comment by Ayush215mb** [comment]
![image](https://github.com/user-attachments/assets/07c35383-65c7-48a7-8389-4b72d3167d59)
Give your review for this UI and any change if you want.

**Comment by adarsh-site** [comment]
Nice ❤️
Please make sure to review all the recent changes and incorporate them as well.
Just one suggestion: Add the "generate password" button to the right of the password field.

**Comment by Ayush215mb** [comment]
@jinx-vi-0 Please clarify this.
shall I change the "Save" to "generate password" and move it beside the password field??

**Comment by adarsh-site** [comment]
No.
There has been some changes in the repo. A new generate password button has been added.

**Comment by Ayush215mb** [comment]
okay I will synchronize the changes and create a PR tomorrow morning.
