### ISSUE TITLE
Enhance password field

### ISSUE THREAD

**Issue by adarsh-site** [jinx-vi-0/passop#19]
Add similar criteria to the password input to enhance the password validation mechanism for users.

![image](https://github.com/user-attachments/assets/67b20ecc-e36c-4292-ac3a-07609c93fc63)

**Comment by AskitEndo** [comment]
@jinx-vi-0  @jindalpriyanshu101 Is this something I can work Upon?

**Comment by jindalpriyanshu101** [comment]
If you think you can, then kindly let us know your approach ;D

**Comment by adarsh-site** [comment]
@AskitEndo someone already working on this.

**Comment by AskitEndo** [comment]
> If you think you can, then kindly let us know your approach ;D

I was thinking of tracking the user typing the passwaord using hooks,each time the the user types it is compared with the the criteria, all made possible using the React state,then just simply hover display the tooltip box

**Comment by kashikaga** [comment]
@jinx-vi-0 please assign me this issue with the labels of level,hacktoberfest and gssoc extended

**Comment by srujanaaac** [comment]
@jinx-vi-0  Can I work on this? 
Solution:
Password Strength Meter:

Implement a visual bar (weak, medium, strong) that updates in real-time as users type.
Criteria: 8-20 characters, at least one capital letter, one number, and no spaces.
Real-time Validation:

Display validation rules dynamically with color-coded feedback (green for valid, red for invalid).
Criteria include:
8-20 characters
At least one uppercase letter
At least one number
No spaces
Frontend and Logic:

Use HTML/CSS for UI, JavaScript for real-time validation.
Update the UI and strength meter based on regex rules and typing events.
Benefits:
Immediate feedback helps users create strong passwords.
Enhances security and improves user experience.

**Comment by adarsh-site** [comment]
Assigned @FazeZxc
