### ISSUE TITLE
Assign Favicon for Password Entries

### ISSUE THREAD

**Issue by Nimrat0199** [jinx-vi-0/passop#20]
The goal is to assign a favicon or small icon representing the website for which the password is saved.  

To achieve this, I propose using the following Google favicon service:  
https://www.google.com/s2/favicons?domain=${domain}&sz=${size}

for eg :  [  img src="https://t3.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=http://geeksforgeeks.org&size=128" ]

By using this service, we can dynamically fetch and display the favicon for any domain. 
Please assign this issue to me under GSSOC'24 extd   hacktoberfest-accepted .

**Comment by adarsh-site** [comment]
@Nimrat0199 Will it show the icon of the website that's been saved ?

**Comment by Nimrat0199** [comment]
yes , so whenever user saves a password and the entry is added in the table , it will display the icon before that website

**Comment by adarsh-site** [comment]
Assigned @Nimrat0199

**Comment by Nimrat0199** [comment]
could you also please assign a level

**Comment by adarsh-site** [comment]
I'll add it after reviewing your pr.

**Comment by Nimrat0199** [comment]
ok thankyou
