### ISSUE TITLE
Website Dark Mode UI 

### ISSUE THREAD

**Issue by AskitEndo** [jinx-vi-0/passop#22]
The website is missing **Darkmode** toggle button, which when clicked switch the website into dark mode friendly UI

And on which further functionality can be defined.

**Comment by AskitEndo** [comment]
@jindalpriyanshu101 @jinx-vi-0 
Do assign me this feature , as I wanna work on it,
Also add the Appropriate level and Info tags

**Comment by jinx-vi-0** [comment]
Assigned @AskitEndo
