### ISSUE TITLE
Adding the feature of automatic random password generator.

### ISSUE THREAD

**Issue by aryadevesh** [jinx-vi-0/passop#24]
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/4ad778b9-3871-44ac-b87b-086592872447">
Adding the button near password input box to automatically generating the password. This is crucial for your project.

**Comment by adarsh-site** [comment]
It should be an optional feature. If the user wants to add a random password, they can do so. However, you need to take care of some issues, such as ensuring that no two generated passwords are the same. You could use the URL and username to generate a password. Also, make sure that the generated password is valid.

**Comment by aryadevesh** [comment]
I also meant it as an optional feature only and I will take for the things you mentioned.

**Comment by adarsh-site** [comment]
Assigned @aryadevesh
