### ISSUE TITLE
Feature: Save Current data Button | Import & Export Data

### ISSUE THREAD

**Issue by AskitEndo** [jinx-vi-0/passop#26]
As the Service works on device to device locally, I want to work on the button which allows the user to one click download all the passwords in a single Document File.

This Feature can also be further enhanced as import and export passwords feature,

**Comment by AskitEndo** [comment]
@jindalpriyanshu101 @jinx-vi-0 Can I work on this? Also add the appropriate tags on the issue

**Comment by adarsh-site** [comment]
Assigned @AskitEndo
