### ISSUE TITLE
Implementing JWT Authentication and Authorization in password/email

### ISSUE THREAD

**Issue by Priyatosh11** [jinx-vi-0/passop#30]
Here is how JWT Works for Authentication
User Login:

When a user logs in with their credentials (e.g., email and password), the server validates these credentials.
If the login is successful, the server generates a JWT and sends it back to the client.
JWT Structure: A JWT consists of three parts:

Header: Contains metadata about the token, such as the signing algorithm used (e.g., HMAC, RSA).
Payload: The data being transmitted, such as user ID or roles. It contains claims (e.g., user ID, expiration time).
Signature: Created by encoding the header and payload using a secret key. It ensures that the token hasn't been altered.

@jinx-vi-0 I am interested to work on the above issue raised by me, please assign me this issue of adding JWT secure authentication

**Comment by jindalpriyanshu101** [comment]
Assigned. You're good to go @Priyatosh11

**Comment by harsh0853** [comment]
Hey! Can you please assign this to me ?

**Comment by jindalpriyanshu101** [comment]
> Hey! Can you please assign this to me ?

please explain your approach first

**Comment by VinaySatrasala** [comment]
### **Hello i want to work on this issue,**
###  **assign it to me**
### here is the explanation how i want to do it.if and changes need to be done please do let me know.
### Register User

This route (`/register`) allows the creation of new users with hashed passwords using `bcrypt`.

### Login Route

The `/login` route checks if the provided credentials are valid. If successful, it generates a JWT signed with a secret key, which expires after 1 hour (`expiresIn: '1h'`).

### JWT Middleware

The `authenticateJWT` middleware checks for a JWT token in the request headers (in the `Authorization` field) and verifies it. If valid, it attaches the decoded user data to `req.user` and allows access to protected routes.

**Comment by Balamurugan-cyber** [comment]
Could you please assign this issue

**Comment by jindalpriyanshu101** [comment]
> Could you please assign this issue

Explain your approach buddy

**Comment by Balamurugan-cyber** [comment]
> > Could you please assign this issue
> 
> Explain your approach buddy
Develop the user interface for the Login and Signup functionality, with form validation and integration with the backend API for user registration and authentication.

Tasks:

Design a Signup form with fields: username, email, and password.
Design a Login form with fields: email/username and password.
Perform input validation (password strength, valid email, etc.).
Provide user feedback for successful or failed registration/login attempts.
Redirect users to the dashboard after successful login.
Ensure the UI is responsive and user-friendly.
Feature Requirements:

Integrate the forms with the backend API for user registration and authentication.
Store JWT tokens in local storage or cookies for session management after login.
Display error messages for invalid credentials or form errors.
Handle successful registration/login with redirection and session management.

**Comment by jindalpriyanshu101** [comment]
@jinx-vi-0 do we need it? decide and take appropriate action.

**Comment by harshbhar0629** [comment]
@jindalpriyanshu101 Do you want login and signup functionality using JWT..??? Please assign to me:)
