### ISSUE TITLE
Adding a update button

### ISSUE THREAD

**Issue by Nimrat0199** [jinx-vi-0/passop#33]
Whenever we want to update a password , instead of save button there should be an update button . 
So what we can do is change the text inside the button to change between "save" and "update" based on if the form has id or not .

![Screenshot 2024-10-05 092423](https://github.com/user-attachments/assets/47c83468-3612-4504-95f2-4c0e89a6597a)

**Comment by adarsh-site** [comment]
Assigned @Nimrat0199
