### ISSUE TITLE
backend code improvement

### ISSUE THREAD

**Issue by trahulprabhu38** [jinx-vi-0/passop#34]
the readability of backend can be improved by sorting into the required folders.If you assgin me this i can fix it immediately.

**Comment by jindalpriyanshu101** [comment]
Hi, @T-Rahul-prabhu-38. as this is just re-organization of folders, i can't give you any levels on this issue. i'd suggest you to improve the documentation appropriately along with this change, to achieve a level.

**Comment by trahulprabhu38** [comment]
ohh, if i do both will that be level2?

**Comment by jindalpriyanshu101** [comment]
Level 1. since there's no code involved.

**Comment by trahulprabhu38** [comment]
oh ok fine, ill do that

**Comment by jindalpriyanshu101** [comment]
Alright, you're good to go.

**Comment by jindalpriyanshu101** [comment]
Any update? @T-Rahul-prabhu-38

**Comment by trahulprabhu38** [comment]
im sorry , i lost this amongst other issue , ill fix it by tonight.

**Comment by jindalpriyanshu101** [comment]
No update yet, would you let me know if you're working on it or not? @T-Rahul-prabhu-38
