### ISSUE TITLE
Upload .env.example, Remove .env, and Update .gitignore for Smoother Development

### ISSUE THREAD

**Issue by rishyym0927** [jinx-vi-0/passop#36]
**Title:** Upload `.env.example`, Remove `.env`, and Update `.gitignore` for Smoother Development

**Description:**
To ensure smoother collaboration and deployment, we need to make the following changes:
1. **Upload a `.env.example` file:**  
   This file should include all the necessary environment variables without any sensitive information (e.g., API keys, database credentials). It will serve as a reference for other developers to create their own `.env` files.
   
2. **Remove the `.env` file from the repository:**  
   Sensitive information should not be committed to version control. We'll remove the existing `.env` file from the repository to ensure it isn't exposed.

3. **Update `.gitignore`:**  
   Add the `.env` file to `.gitignore` to prevent it from being accidentally committed in the future.

**Tasks:**
1. Create a `.env.example` file with placeholder values.
2. Remove the `.env` file from the repository.
3. Update `.gitignore` to exclude `.env`.

**Level:** GSSOC Level 3

**Assigned To:** @mention (or "To Be Assigned")

**Comment by adarsh-site** [comment]
You don't need to raise an issue just for this. I'm not going to add any level just for this.
