### ISSUE TITLE
Automate GitHub Tagging and labelling of prs and issues

### ISSUE THREAD

**Issue by shubhagarwal1** [jinx-vi-0/passop#42]
I propose to work on GitHub Actions workflow to automate the creation of labels. The workflow is triggered when a new commit is pushed, generating labels accordingly to it
@hey @jinx-vi-0 can you please assign it to me .

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
and please add gssoc label

**Comment by adarsh-site** [comment]
There is no need for that.
