### ISSUE TITLE
Update readme.md with feature in table

### ISSUE THREAD

**Issue by ananyag309** [jinx-vi-0/passop#43]
I just saw that in main readme file big images of gssoc and hactoberfest is present it will look more organised if we implement something like this

if need please assign this issue to me

![featured in](https://github.com/user-attachments/assets/55c4eaea-23f9-4df6-be78-7eb67fd1b58c)

**Comment by adarsh-site** [comment]
@ananyag309 
You can work on this, but I won't add any levels to it.

**Comment by ananyag309** [comment]
ok
but atlease add my name in assignes and open source label

**Comment by lakshmirajvagu** [comment]
@jinx-vi-0 I would like to work on it
