### ISSUE TITLE
Add Star Rating Feature to Footer

### ISSUE THREAD

**Issue by jvkousthub** [jinx-vi-0/passop#47]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when users cannot easily provide feedback on our application. Currently, there is no quick and intuitive way for users to rate our application directly from the interface. This makes it harder to gather user feedback and improve the application based on user ratings.

**Describe the solution you'd like**
I would like to add a star rating feature to the footer of our application. This feature will allow users to rate our application by clicking on stars (1 to 5). The selected rating should be visually highlighted, and the rating should be captured for further processing (e.g., sending to a server).

**Describe alternatives you've considered**
Adding a separate feedback form page: This would require users to navigate away from the current page, which might reduce the likelihood of them providing feedback.
Using a third-party feedback widget: This could introduce dependencies and might not integrate seamlessly with our application's design.

**Additional context**

**Comment by jindalpriyanshu101** [comment]
> I would like to add a star rating feature to the footer of our application. This feature will allow users to rate our application by clicking on stars (1 to 5). The selected rating should be visually highlighted, and the rating should be captured for further processing (e.g., sending to a server).

Have you considered the case when users actually gave their feedback, then what to do? Because we won't be asking for feedback all the time through footer at all? 

And, where are those feedbacks are going to be stored & shown?

Do let me know your approach about how you'll tackle it?

**Comment by jindalpriyanshu101** [comment]
No updates on the issue yet, Closing.
