### ISSUE TITLE
Better URL implementation

### ISSUE THREAD

**Issue by AskitEndo** [jinx-vi-0/passop#49]
**Is your feature request related to a problem? Please describe.**
When ever the password is not saved , because the user has not entered a proper URL, the Notification Toast doesn't
clarify this exact reason properly leaving the user in an  Confusion state.

**Describe the solution you'd like**
A clear Indication just like the password feature.

**Comment by AskitEndo** [comment]
@jindalpriyanshu101 @jinx-vi-0 Do observe and assign, as I'll implement this Asap.

**Comment by adarsh-site** [comment]
Assigned @AskitEndo

**Comment by AskitEndo** [comment]
@jinx-vi-0 Do review as the requested updates have been applied!
