### ISSUE TITLE
Deploy it is on Vercel for enhanced contributer exp on repository.

### ISSUE THREAD

**Issue by tarunkumar2005** [jinx-vi-0/passop#56]
**Is your feature request related to a problem? Please describe.**
Deploy it is on Vercel for enhanced contributer exp on repository.

**Describe the solution you'd like**
Deploying this website on vercel

@jinx-vi-0 @jindalpriyanshu101 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by jindalpriyanshu101** [comment]
Hey @tarunkumar2005 deploying on vercel etc are done by repository owners, it's not a thing you can contribute to.

**Comment by tarunkumar2005** [comment]
@jindalpriyanshu101 Okay i saw many issues like this in other repos so i though i should try this too. I will keep in mind i provide value adding contributions.
