### ISSUE TITLE
Implement Password Hashing, Migrate to Atlas & Deployment

### ISSUE THREAD

**Issue by divy-03** [jinx-vi-0/passop#58]
Currently, passwords are stored in plain text, which poses a security risk. Additionally, the website is using a local MongoDB server, limiting scalability and access for deployment.

Proposed Solutions: 
1. Implement Secure Password Hashing: I will integrate bcrypt to hash passwords before storing them in the database, significantly improving security.
2. Migrate to MongoDB Atlas: I will refactor the backend to connect to MongoDB Atlas, leveraging its cloud-hosted infrastructure to ensure scalability, global accessibility, and improved database performance.
3. Deploy to Cloud Platforms: I will deploy both the backend and frontend to a cloud platform like Render or Vercel, ensuring smooth and scalable production environments.

Once assigned, I will:

1. Modify the codebase to implement bcrypt hashing.
2. Migrate the database to MongoDB Atlas.
3. Deploy the application for seamless, scalable access.

Please assign this issue to me and label it appropriately. I’m confident I can implement these improvements efficiently and securely.

Thank you!

**Comment by adarsh-site** [comment]
Assigned @divy-03

**Comment by harshbhar0629** [comment]
@jinx-vi-0 Can i work on this issue??

**Comment by ar1701** [comment]
As i can see this issue is still open and not resolved yet inspite of it is already assigned. So @jinx-vi-0 if u will assign it to me i will complete it by today itself.

Proposed Solution:-
1. The password will store in Hashform in MongoAtlas DB
2. And i can deploy it on render.com
