### ISSUE TITLE
bug while updating ,  updated text are not saved in database

### ISSUE THREAD

**Issue by abhayksahu369** [jinx-vi-0/passop#68]
**Describe the bug**

- bug while updating ,  updated text are not saved in database and also changes are not shown in table

**To Reproduce**

- click on update(pen) icon 
- try to update text 
- click on update button

**Expected behavior**

- to saved the updated text in database and show the updated text on table.

**Additional context**

- please verify it and assign this task to me . Thank you

**Comment by jindalpriyanshu101** [comment]
@abhayksahu369 Can you share the visual representations of this bug? (Screenshots might help.)

**Comment by abhayksahu369** [comment]
@jindalpriyanshu101 

https://github.com/user-attachments/assets/2dde2f12-1aa4-4071-91b5-cb45dc655c60

**Comment by abhayksahu369** [comment]
@jindalpriyanshu101 

https://github.com/user-attachments/assets/6eaff42d-ac31-4c6e-8c97-08479e780299

**Comment by jindalpriyanshu101** [comment]
Alright then, you can start working on it @abhayksahu369 :D, Assigned.
