### ISSUE TITLE
Login Feature for user

### ISSUE THREAD

**Issue by Sawan-Kushwah** [jinx-vi-0/passop#69]
As now as we go on our website it should all the password 
but we can build a login feature which show the password only when user is logged in 
and this will also help us in maintaining on deployment as user can view his all password just by login in on app

**Comment by adarsh-site** [comment]
Only add sign In/ sign up using google

**Comment by Sawan-Kushwah** [comment]
Okay i will do it

**Comment by jindalpriyanshu101** [comment]
> Okay i will do it

@Sawan-Kushwah You're good to go then, Assigned.

**Comment by hritika2409** [comment]
@jindalpriyanshu101 Can  you please assign me this task?

**Comment by jindalpriyanshu101** [comment]
> @jindalpriyanshu101 Can  you please assign me this task?

Its already assigned to sawan.

**Comment by hritika2409** [comment]
Is there anyother task in which i can help you? @jindalpriyanshu101

**Comment by jindalpriyanshu101** [comment]
> Is there anyother task in which i can help you? @jindalpriyanshu101 

You can surely checkout listed unassigned issues. Or can create one if you have any new useful feature in mind ;D

**Comment by abhayksahu369** [comment]
@Sawan-Kushwah how's your work going on, do you want any help?

**Comment by Sawan-Kushwah** [comment]
@abhayksahu369 i will make PR today ⭐

**Comment by abhayksahu369** [comment]
@Sawan-Kushwah okay, all the best!

**Comment by Sawan-Kushwah** [comment]
@abhayksahu369 done checkout pull request #86 
if you need changes please tell me

**Comment by adarsh-site** [comment]
great work @Sawan-Kushwah

**Comment by Sawan-Kushwah** [comment]
@jinx-vi-0 Thank you soo much !! Ready to do more contribution to your project

**Comment by adarsh-site** [comment]
If you enjoyed contributing, please consider giving us a star on GitHub and following us for updates!
