### ISSUE TITLE
Missing password validation 

### ISSUE THREAD

**Issue by kashikaga** [jinx-vi-0/passop#7]
Missing validation logic to ensure passwords include capital letters, small letters, numeric digits, and special characters, and are at least 8 characters long.
@jinx-vi-0 kindly assign this issue to me

**Comment by adarsh-site** [comment]
Assigned @kashikaga

**Comment by kashikaga** [comment]
@jinx-vi-0 
@jindalpriyanshu101 
could you please add the level label for it ?
