### ISSUE TITLE
Improving the nav bar and its features more responsive and reactive

### ISSUE THREAD

**Issue by hritika2409** [jinx-vi-0/passop#74]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adarsh-site** [comment]
If you are suggesting a UI enhancement, please include screenshots. Words alone may not fully convey your proposal.

**Comment by lakshmirajvagu** [comment]
@jinx-vi-0 I would like to work on it
