### ISSUE TITLE
while deleting a single password all the passwords are deleted 

### ISSUE THREAD

**Issue by AyushSharma72** [jinx-vi-0/passop#78]
**Describe the bug**
when deleting a single password it should only delete that password but all the passwords are deleted

**Expected behavior**
only one password should be deleted 

please assign this issue to me @jinx-vi-0

**Comment by adarsh-site** [comment]
It is working perfectly.

**Comment by AyushSharma72** [comment]
> It is working perfectly

no it is not atleast on the deployed version

**Comment by AyushSharma72** [comment]
> It is working perfectly.

may be you did not understand

**Comment by adarsh-site** [comment]
Message on the Discord thread. We will discuss it there.

**Comment by AyushSharma72** [comment]
> Message on the Discord thread. We will discuss it there.

oh sorry its working fine
