### ISSUE TITLE
Working on the Backend Code Quality 

### ISSUE THREAD

**Issue by MOHINI1403** [jinx-vi-0/passop#8]
Currently all the code is written into the `server.js` file which is not considered as a good industry practise . Please assign me this issue so that I could work on this and improvise the quality.

**Comment by jindalpriyanshu101** [comment]
Can you elaborate more about your implementation?

**Comment by RchtDshr** [comment]
I think they meant following the MVC architecture. Creating a proper folder structure for model, controllers, and routes which improves the readability and understanding of the code base, which currently is written all in one file ie server.js . I can resolve this and improve the folder structure.

**Comment by MOHINI1403** [comment]
I am not only talking about working on the MVC architecture you can connect with me on discord I will elaborate my approach over there .

**Comment by MOHINI1403** [comment]
mohinichauhan_ This is my discord username.

**Comment by srujanaaac** [comment]
@jindalpriyanshu101 we can create production grade folders routes, controllers, DB, models
