### ISSUE TITLE
Feature Request: Add Browser Extension for Autofill

### ISSUE THREAD

**Issue by algonomad571** [jinx-vi-0/passop#80]
I would like to suggest adding a browser extension for PassOP that automatically fills saved credentials into website login forms. The extension should include:

- **Manifest configuration** for permissions and background scripts.
- **Content script** to detect and autofill password fields.
- **Popup interface** where users can fetch credentials from the backend.
- **Communication with backend** to retrieve saved credentials.

This feature would enhance user convenience and improve PassOP's usability.

**Comment by algonomad571** [comment]
Please assign me this issue under GSSoC and Hacktoberfest

**Comment by adarsh-site** [comment]
Assigned @muskan171105

**Comment by algonomad571** [comment]
Please check my PR and merge it if everything is fine

**Comment by adarsh-site** [comment]
great work 👍
