### ISSUE TITLE
Code Cleanup: Organising folder structure into frontend, backend and README

### ISSUE THREAD

**Issue by pranavajith** [jinx-vi-0/passop#82]
**Is your feature request related to a problem? Please describe.**

The README.md seems to indicate that the folder structure is as follows
PassOP/
├── backend/ # Backend Node.js application
│   ├── server.js # Main server file
│   ├── .env # Environment configuration (not included in repo)
│   ├── package.json # Backend dependencies
│   └── ... # Other backend files
├── frontend/ # React frontend application (using Vite)
│   ├── src/ # React components and files
│   ├── public/ # Public static files
│   ├── package.json # Frontend dependencies
│   └── vite.config.js # Vite configuration file
├── README.md # This file
└── ...

Whereas, currently that is not the case. This caused me a lot of confusion initially, and I'd imagine it is the same for many people.

**Describe the solution you'd like**
I would like to first organise the files into frotnend and backend folder, and then update the README to match this.

**Describe alternatives you've considered**
We could simply change the README to fit the current structure,, but the current structure is not the most widely seen uniform seperation of concerns of frontend and backend, and so it is not ideal.

**Additional context**
Will add any that is needed by admin. As of now, seems self explanatory.

**Comment by pranavajith** [comment]
@jinx-vi-0 Do you mind setting up relevant labels and assigning it to me? Although I have some experience in dev, It's always been solo projects, never really open source. Looking forward to do my best here!

**Comment by adarsh-site** [comment]
Okay, sounds good! Just make sure to check every endpoint and configuration to ensure everything works perfectly. Also, please update the README to reflect any changes you make. Looking forward to your contributions!

**Comment by pranavajith** [comment]
Will do!
In the meantime, wanted to ask if .env being in backend folder is required. Isn't it supposed to be in gitignore?
Also, as a follow up, isn't there supposed to be a single gitingore? Why does there seem to be 2?

@jinx-vi-0

**Comment by adarsh-site** [comment]
Yeah, add the .env to gitignore and create an example.env to help contributors understand the .env structure.

**Comment by pranavajith** [comment]
@jinx-vi-0 is there any issue with the export option? It doesn't seem to work. I reverted all my changes, but it still seems to not respond?

**Comment by pranavajith** [comment]
@jinx-vi-0 
Also... noted a major issue in backend.

The download doesn't happen cause of the following reason. In server.js,

![image](https://github.com/user-attachments/assets/d21ebdd2-8f4b-4250-8b70-5ec552d02d4f)


This expects id as a parameter. Which means anything after "http://localhost:3000/" will be seen as the id parameter. Hence when we try to export passwords, it is unable to reach the handler:

![image](https://github.com/user-attachments/assets/af3ea835-cdcb-4bf4-bf5d-9c8a1b25f097)

Leading to error.

Check it out yourself. Once you comment out the /:id handler, the export option works. This is a major backend flaw. Would you like me to make an issue for the same?

**Comment by adarsh-site** [comment]
@pranavajith create an issue. I'll assign it to you.

**Comment by jindalpriyanshu101** [comment]
Hi, @pranavajith what's the progress status on this issue?

**Comment by jindalpriyanshu101** [comment]
Marked as Up-To-Grab since there's no update yet.

**Comment by 112201007** [comment]
@jinx-vi-0 Could you please assign this to me? I’ve been exploring open source projects, and I’ll do my best to contribute and resolve it.
