### ISSUE TITLE
Issue Title: "Add Chatbot Feature"

### ISSUE THREAD

**Issue by AswaniBolisetti** [jinx-vi-0/passop#83]
@jinx-vi-0 
Issue Description: I would like to add a chatbot feature to the website to enhance user support and engagement. The chatbot will provide instant assistance to users by answering common queries, offering guidance, and directing them to relevant sections of the site.

Please assign this issue to me under the labels: level3, gssoc-ext, and hacktoberfest-accepted.

**Comment by adarsh-site** [comment]
Can you please help me understand why a password management website needs a chatbot?

**Comment by AswaniBolisetti** [comment]
@jinx-vi-0 actually i thought the same,
