### ISSUE TITLE
adding follow us section

### ISSUE THREAD

**Issue by AswaniBolisetti** [jinx-vi-0/passop#84]
I would like to work on this feature, could you please assign me this

**Comment by adarsh-site** [comment]
Please explain your approach in detail and follow the template when raising an issue.

**Comment by AswaniBolisetti** [comment]
@jinx-vi-0 I would like to add a side bar for social icons, or i can add the follow us on section in footer also,

**Comment by PulkitShubham** [comment]
@jinx-vi-0 Please assign me this issue I would enhance the overall UI

**Comment by AswaniBolisetti** [comment]
@jinx-vi-0 could you please add the level tag too

**Comment by adarsh-site** [comment]
> @jinx-vi-0 could you please add the level tag too

I'll add it after reviewing the pr.

**Comment by AswaniBolisetti** [comment]
@jinx-vi-0 
I have solved this one and created pull request, kindly review it
