### ISSUE TITLE
Add Contributors Page to Display Project Contributors

### ISSUE THREAD

**Issue by pani2004** [jinx-vi-0/passop#87]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

The contributors page will display the details of the contributors who have contributed to this project

**Additional context**
Since this repo is part of a open source program it would be great to have a contributors page

**Comment by pani2004** [comment]
@jindalpriyanshu101 @jinx-vi-0 Can I work on this? Open source programme - GSSoC and Hacktoberfest

**Comment by adarsh-site** [comment]
We are no longer accepting any documentation-related issues. If you still want to proceed with this, you are good to go. However, please note that this issue will not receive any level.

**Comment by pani2004** [comment]
@jinx-vi-0 Will add the page to the website not in Readme File. Ex of my work - 

https://github.com/user-attachments/assets/2c6a635b-43f1-49fa-92b7-f88c8905d191

**Comment by adarsh-site** [comment]
Thank you for your effort, but we had not planned anything like that.
