### ISSUE TITLE
Password Strength Meter 

### ISSUE THREAD

**Issue by sv410** [jinx-vi-0/passop#88]
Is your feature request related to a problem? Please describe. I'm always frustrated when I create passwords and am unsure of their strength. Without a clear indication of how strong or weak my password is, it's hard to ensure my accounts are secure.

Describe the solution you'd like I propose adding a password strength meter that visually indicates the strength of the password as the user types. This meter will provide real-time feedback, showing whether the password is weak, medium, or strong. This can help users create more secure passwords.

Describe alternatives you've considered

Third-Party Extensions: Using browser extensions to check password strength, but this approach isn't integrated into the platform and might not be consistent for all users.

Static Guidelines: Providing written guidelines on creating strong passwords. While helpful, they don't offer real-time feedback, which is crucial for immediate improvement.

External Tools: Using external websites for password strength checking, but this requires users to navigate away from PassOP, disrupting their workflow.

Additional context

**Comment by adarsh-site** [comment]
Password strength varies depending on the context. How can you ensure if a password is strong or weak? For example, if a user is just adding their name with a special character and 2-3 numbers, how would you consider this?

**Comment by sv410** [comment]
@jinx-vi-0 Password strength depends on length, complexity, and uniqueness. A name with a special character and numbers (e.g., "John@123") is weak. To create a strong password, aim for 12-16 characters, mixing uppercase, lowercase, numbers, and symbols. by Avoiding common words and predictable patterns for enhanced security.

**Comment by adarsh-site** [comment]
We are already checking for capital letters, special characters, and numbers. If we implement both functionalities, it would be chaotic. We can either provide suggestions to follow the above-mentioned rules or use a strength meter. What do you think about this? We can discuss this over discord dm or in the passop thread.

**Comment by sv410** [comment]
@jinx-vi-0 I agree that combining both functionalities could be chaotic. Providing clear suggestions for password rules might enhance user experience without overwhelming them. A strength meter can also be effective, but it might complicate things.

**Comment by adarsh-site** [comment]
Exactly
