### ISSUE TITLE
Need to generate dummy data for imported changes to be visible.

### ISSUE THREAD

**Issue by pranavajith** [jinx-vi-0/passop#89]
**Describe the bug**
Even after importing, the passwords are not visible until one inputs another password.

**To Reproduce**
1. Create a passwords.json file ready to be imported (or add data in browser, export, and then clear from browser).
2. Import it.
3. Observe the updation.
4. Add a new password.

**Expected behavior**
It is expected that as soon as the import is done, the component re-renders.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Comment by adarsh-site** [comment]
Assigned @pranavajith

**Comment by jindalpriyanshu101** [comment]
Any update? @pranavajith
