### ISSUE TITLE
Missing : Password Encryption 

### ISSUE THREAD

**Issue by MOHINI1403** [jinx-vi-0/passop#9]
The passwords are  right now stored into the  `Mongo DB` Database directly without hashing the password this is creating security risk for the users to store their password . Proper cryptography need to applied in order to ensure that the passwords are stored into the database into the secure manner. 
Please assign me this issue so that I could continue working on this issue.

**Comment by jindalpriyanshu101** [comment]
Assigned @MOHINI1403, you're good to go ahead.

**Comment by MOHINI1403** [comment]
Sure I will work on this

**Comment by harsh0853** [comment]
Hey! Can you please assign this to me ?
