### ISSUE TITLE
Adding eye button in password field in Signup/login Page

### ISSUE THREAD

**Issue by pani2004** [jinx-vi-0/passop#92]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Will add a eye button in the password field for toggling visibility.

**Additional context**
![12 10 2024_20 39 09_REC](https://github.com/user-attachments/assets/9561afd4-3248-4b0b-bdfd-d9e768f6abbc)

**Comment by pani2004** [comment]
@jinx-vi-0 can I work on this?

**Comment by adarsh-site** [comment]
Assigned @pani2004
