### ISSUE TITLE
Unappealing and Disproportionate Footer Design

### ISSUE THREAD

**Issue by TornovDutta** [jinx-vi-0/passop#93]
# About:
The footer is too small and lacks visual balance, making it appear cramped and unappealing. The text size and layout are not proportional to the rest of the page, giving it an unfinished look. The heart icon appears awkwardly placed and does not blend well with the overall design. Additionally, there’s insufficient padding or spacing around the elements, which further detracts from its aesthetics. Enhancing the size, adding more spacing, and improving the layout would significantly boost the visual appeal and readability of the footer.

### sceenshot:
![Screenshot 2024-10-13 013524](https://github.com/user-attachments/assets/feeef8f0-d6b2-42dc-99f7-1b126f6db566)

**Comment by TornovDutta** [comment]
@jinx-vi-0 please label the issuse and assign it to me

**Comment by adarsh-site** [comment]
you're good to go.

**Comment by TornovDutta** [comment]
Please Label the level of this issuse.
@jinx-vi-0

**Comment by TornovDutta** [comment]
@jinx-vi-0 please check my PR
