### ISSUE TITLE
Add a Home Page for Better Navigation and User Experience

### ISSUE THREAD

**Issue by Tamanna225** [jinx-vi-0/passop#94]
Currently, the website includes login, signup, and a password generator page. However, there is no central home page that serves as a starting point for users which contains information and features provided by the website.

I propose adding a home page that users land on. This home page would provide a simple overview of the site

This page would give users a comprehensive overview, helping them understand what the site offers. The features of the site and what the website is all about.

Please assign me this issue with gssoc and hacktoberfest labels

**Comment by adarsh-site** [comment]
Assigned @Tamanna225
