### ISSUE TITLE
Improve Mobile UI Layout

### ISSUE THREAD

**Issue by Nimrat0199** [jinx-vi-0/passop#98]
The current mobile layout of the website has some UI/UX issues . I would like to improve it . Please assign this issue to me .
![Screenshot 2024-10-13 215748](https://github.com/user-attachments/assets/168a9d57-8f55-41d3-bb82-05b2307dd7c3)

**Comment by Jainpaswan** [comment]
assign this to me ... i will make it responsive for mobile screen..

**Comment by adarsh-site** [comment]
Assigned @Nimrat0199

**Comment by adarsh-site** [comment]
🎉 Awesome work
